sonar.projectKey=sathishindira_equal_experts
sonar.organization=sathishindira

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=.